config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get 'friends'
      get 'people'
      post 'send_friend_request'
      get 'pending_friend_requests'
      post 'accept_friend_request'
    end
  end

  mount Commontator::Engine => '/commontator'
  resources :posts
  root 'dashboard#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_friendship
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  acts_as_commontator

  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture, allow_destroy: true
  validates_presence_of :firstname, :username, :lastname
  validates :username, format: {with: /\A[a-zA-Z\d]+\z/, :message => "can only contain letters and numbers."}
  validates :firstname, :lastname, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def friends
    @friends = current_user.friends
  end

  def people
    @users = User.where.not(id: [current_user.id, current_user.friends.pluck(:id)])
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:firstname, :username, :lastname, :avatar, :email, :password, :confirmation_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def friend(user)
    current_user.friends_with?(user)
  end
end

app/views/users/edit.html.haml
.col-md-5
  = image_tag @user.avatar.url(:medium)
.col-md-5
  #content.col-lg-10.col-sm-10
    %h4 Edit
    = simple_form_for(@user, html: {class: 'form-horizontal'}, wrapper: :horizontal_form) do |f|
      = f.error_notification
      .row
        .form-inputs
          .col-md-12
            = f.input :username
            = f.input :email, required: true, autofocus: true
            = f.input :firstname
            = f.input :lastname
            = f.input :avatar, as: :file
        .form-actions
          = f.button :submit, "Update", class: 'btn btn-primary btn-sm'
          = link_to "Back", root_path, class: 'btn btn-danger btn-sm'

app/views/users/friends.html.haml
.mid-form
  %table.table
    %thead
      %th Name
    %tbody
      - @friends.each do |user|
        %tr
          %td= user.firstname

app/views/users/pending_friend_requests.html.haml
.mid-form
  %table.table
    %thead
      %th Name
      %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= user.firstname
          %td= link_to 'Accept Request', accept_friend_request_user_path(user), class: 'btn btn-primary', method: :post

app/views/users/people.html.haml
.mid-form
  %table.table
    %thead
      %th Name
      %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= user.firstname
          %td
            - if friend(user)
              = label_tag 'Connected'
            - else
              = link_to 'Send Request', send_friend_request_user_path(user), class: 'btn btn-primary', method: :post

app/views/users/show.html.haml
.col-md-5
  = image_tag @user.avatar.url(:medium)
.col-md-5
  %h3 View User
  = simple_form_for @user, html: {class: 'form-horizontal'} do |f|
    = f.input :username, as: :string, disabled: true
    = f.input :firstname, as: :string, disabled: true
    = f.input :lastname, as: :string, disabled: true
    = link_to 'Back', root_path, class: 'btn btn-info'