config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get 'friends'
      get 'people'
      post 'send_friend_request'
      get 'pending_friend_requests'
      post 'accept_friend_request'
    end
  end

  mount Commontator::Engine => '/commontator'
  resources :posts
  root 'dashboard#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commontable
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(user_id: [current_user.id, current_user.friends.pluck(:id)])
    @posts = Post.where(user_id: [User.first.id, User.first.friends.pluck(:id)])
  end

  def new
    @post = Post.new
    @post.pictures.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    commontator_thread_show(@post)
  end

  def delete
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:content, :accessible_by, pictures_attributes: [:collage])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.mid-form
  = simple_nested_form_for @post, html: {class: 'form-horizontal'} do |f|
    = f.input :content, as: :string
    = f.input :accessible_by, collection: ['Friends', 'Public'], include_blank: false
    = f.simple_fields_for :pictures, @post.pictures do |pic|
      = pic.input :collage, as: :file
    = f.link_to_add 'Add Picture', :pictures, id: 'add_picture', class: 'btn btn-primary'
    = f.submit 'Save', class: 'btn btn-primary'
    = f.submit 'Cancel', class: 'btn btn-info'

app/views/posts/edit.html.haml
%center
  %h3 Edit Post
= render 'form'

app/views/posts/index.html.haml
= link_to 'Create New Post', new_post_path, class: 'btn btn-primary'
.mid-form
  .col-md-10
    %center
      %h3 All Posts
    %br
    - @posts.each do |post|
      = post.content
      - post.pictures.each do |pic|
        = image_tag pic.collage.url(:thumb)
      %br
      = 'Posted on'
      = post.created_at.strftime('%d-%m-%Y')
      - if post.user_id == current_user.id
        = link_to 'Edit / View', edit_post_path(post), class: 'btn btn-primary btn-sm'
        = link_to 'Delete', post_path(post), class: 'btn btn-danger btn-sm', method: :delete
      = commontator_thread(post)

app/views/posts/new.html.haml
%center
  %h3 New Post
= render 'form'

app/views/posts/show.html.haml
.mid-form
  = simple_form_for @post, html: {class: 'form-horizontal'} do |f|
    = f.input :content, as: :string, disabled: true
    = f.input :accessible_by, collection: ['Friends', 'Public'], include_blank: false, disabled: true
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', posts_path,class: 'btn btn-info'