config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, only: [:edit, :update, :show] do
    member do
      get 'friends'
      get 'people'
      post 'send_friend_request'
      get 'pending_friend_requests'
      post 'accept_friend_request'
    end
  end

  mount Commontator::Engine => '/commontator'
  resources :posts
  root 'dashboard#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include PublicActivity::StoreController

  protected
  def configure_permitted_parameters
    [:username, :firstname, :lastname].each do |user_attr|
      devise_parameter_sanitizer.for(:sign_up) << user_attr
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.haml
- [:notice, :error, :alert].each do |name|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}", :id => name, :style => "display: #{flash[name] ? 'block' : 'none'}", data: {dismiss: 'alert'}}
    - if flash[name]
      = flash[name]

app/views/application/_header.html.haml
.navbar.navbar-inverse.navbar-static-top
  .navbar-header
    = link_to 'Activity', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse
    - if user_signed_in?
      %ul.nav.navbar-nav
        %li= link_to 'Posts', posts_path
      %ul.nav.navbar-nav
        %li.dropdown
          = link_to 'Connections', class: 'dropdown-toggle', "data-toggle" => "dropdown", "aria-expanded" => false do 
            Connections
            %span{class: 'caret'}
          %ul{class: 'dropdown-menu'}
            %li= link_to "Friends", friends_user_path(current_user)
            %li= link_to 'Pending Friend Requests', pending_friend_requests_user_path(current_user)
            %li= link_to "Other Users", people_user_path(current_user)
      %ul.nav.navbar-nav.navbar-right
        = image_tag current_user.avatar.url(:thumb)
        %li.dropdown
          = link_to "#{current_user.username}", class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-expanded' => false do
            #{current_user.username}
            %span.carent
              %ul.dropdown-menu
                %li= link_to 'Profile', edit_user_path(current_user)
                %li= link_to "Logout", destroy_user_session_path, method: :delete
        %li= link_to ""